// ─── Raw listing (as scraped from source, pre-normalization) ───────────────
export interface RawListing {
  source: "centaline" | "midland" | "ricacorp" | "28hse" | "manual";
  sourceUrl: string;
  title: string;
  rawPriceText: string;   // e.g. "698萬", "$6,980,000"
  rawAreaText: string;    // e.g. "實用 450呎"
  rawDistrict: string;    // e.g. "沙田", "新界東"
  fetchedAt: string;      // ISO datetime
}

export type ListingSourceType = "new" | "secondary";
export type ComparisonRole = "primary" | "comparison";

/** Search scope: 新樓為主／只看二手比較／兩者（新樓優先 + 限量二手參考） */
export type MarketFocus = "new" | "secondary" | "all";

// ─── Normalized listing (post-processing, ready for display) ────────────────
export interface NormalizedListing {
  id: string;
  slug: string;
  estateName: string;       // 屋苑名稱 (English name, used as internal key)
  titleEn?: string;         // English project name (explicit; mirrors estateName for 28hse crawls)
  titleZh?: string;         // Chinese project name (Traditional; from Chinese page, no translation)
  buildingName?: string;    // 座向 / 樓號
  /** Listing lifecycle status: "active" | "sold_out" | "coming_soon" | "pending_detail_crawl" | "parse_failed" */
  status?: string;
  district: District;
  subDistrict?: string;     // 更細地區
  address?: string;         // 街道地址
  developer?: string;       // 發展商
  completionYear?: number;  // 預計落成年份 e.g. 2025
  price: number;            // 起價 HKD (0 when price unknown)
  priceMax?: number;        // 最高價 HKD (for new dev price range)
  saleableArea: number;     // 實用面積 (sq ft)
  saleableAreaMax?: number; // 最大實用面積
  grossArea?: number;       // 建築面積 (sq ft, optional)
  psf: number;              // 實用呎價 (0 when price unknown)
  bedrooms: number;         // 房數
  bathrooms?: number;
  propertyType: PropertyType;
  floor?: string;           // e.g. "中層", "高層"
  facing?: string;          // e.g. "南", "山景"
  age?: number;             // 樓齡 (years)
  description?: string;     // 項目介紹 (may be English)
  descriptionZh?: string;   // 中文項目介紹 (preferred; fallback to description)
  source: RawListing["source"];
  sourceUrl: string;
  lastSeenAt: string;       // ISO datetime
  imageUrl?: string;
  tags?: string[];          // e.g. ["鄰近港鐵", "新入伙", "校網"]
  /**
   * "full" = price confirmed; "partial" = price not yet published.
   * undefined = legacy/mock data (treat as "full").
   */
  dataCompleteness?: "full" | "partial";
  /**
   * "normal" = data looks consistent; "suspicious" = one or more validation
   * rules flagged this listing for manual review (e.g. high price + low bedrooms).
   * undefined = legacy/mock data (treat as "normal").
   */
  dataQuality?: "normal" | "suspicious";
  /** 新盤 vs 精選二手（比較用）；由 `applyProductDefaults` 等流程寫入 */
  sourceType?: ListingSourceType;
  comparisonRole?: ComparisonRole;
  /** 與同區新／二手相關的一句比較提示 */
  comparisonSummary?: string;
  /** 精選二手參考盤（非完整市場） */
  isFeaturedComparison?: boolean;
}

// ─── Room-type summary row (one per bedroom type, for detail page table) ──────
export interface RoomTypeSummary {
  id: string;
  unitLabel: string;          // "開放式" | "1房" | "2房" | "3房" | "4房或以上"
  roomCount: number;          // 0 = studio
  minSaleableArea?: number;   // sq ft
  maxSaleableArea?: number;   // sq ft
  minPrice?: number;          // HKD; undefined = 待更新
  maxPrice?: number;          // HKD
  pricePerSqft?: number;      // HKD/sqft (based on min price + min area)
  unitCount?: number;
  /** "available" | "sold_out" | "pending" | "unknown" */
  availability: string;
  /**
   * Data confidence for this room type:
   * - "high":   price + area both present; multiple supporting data points
   * - "medium": partial data (area only, or price only)
   * - "low":    no price and no area; single weak signal only
   */
  confidence: "high" | "medium" | "low";
}

/** @deprecated Use RoomTypeSummary. Kept for mock-data compatibility. */
export interface ListingUnitRow {
  id: string;
  unitLabel?: string;
  roomCount: number;
  saleableArea: number;
  price: number;
  pricePerSqft: number;
}

// ─── AI Insight (generated by AI layer, attached to a listing) ──────────────
export interface AIInsight {
  listingId: string;
  summary: string;          // 1-2 句 AI 摘要
  buyerFit: string;         // e.g. "適合首置家庭"
  riskNote?: string;        // e.g. "樓齡較高，需注意維修費"
  pricePositioning:
    | "below_market"        // 低於市價
    | "at_market"           // 市價水平
    | "above_market";       // 高於市價
  compareTags: string[];    // short tags for compare table, e.g. ["低呎價", "校網好", "新樓"]
  generatedAt: string;      // ISO datetime
}

// ─── Listing with AI enrichment (joined) ───────────────────────────────────
export interface EnrichedListing extends NormalizedListing {
  insight?: AIInsight;
  /** Room-type summaries (attached during search; empty array = no data in DB) */
  roomTypes?: RoomTypeSummary[];
}

/** `gte4` = 4 房或以上（URL 常用 `4plus` 解析而來） */
export type BedroomFilter = number | "gte4" | "";

// ─── Search / filter params ─────────────────────────────────────────────────
export interface SearchParams {
  /**
   * Free-text query — case-insensitive substring match across
   * estateName / titleZh / titleEn / address / developer. Example: "首岸".
   * Even a single Chinese character matches (e.g. "首" finds 「首岸」).
   */
  q?: string;
  /** Canonical district label (Chinese) or any value stored in DB */
  district?: string;
  minPrice?: number;
  maxPrice?: number;
  /** 最高預算選「1500萬以上」：價格 ≥1500 萬（與進階 minPrice 分開標示） */
  priceFloor1500?: boolean;
  bedrooms?: BedroomFilter;
  minArea?: number;
  maxArea?: number;
  /** 新樓為主／二手比較／全部（缺省 = all：新樓優先 + 限量二手） */
  marketFocus?: MarketFocus;
  sortBy?: SortOption;
  /** 只顯示已公布售價的樓盤（排除 partial 記錄） */
  priceKnown?: boolean;
}

// ─── Enums / unions ──────────────────────────────────────────────────────────
export type District =
  | "沙田"
  | "大圍"
  | "馬鞍山"
  | "大埔"
  | "西貢"
  | "將軍澳"
  | "啟德"
  | "九龍站"
  | "奧運"
  | "荃灣"
  | "屯門"
  | "元朗"
  | "天水圍"
  | "北角"
  | "鰂魚涌"
  | "康城"
  | "南昌"
  | "黃竹坑"
  | "九龍城"
  | "觀塘"
  | "深水埗"
  | "尖沙咀"
  | "佐敦"
  | "油麻地"
  | "旺角"
  | "紅磡"
  | "何文田"
  | "葵涌"
  | "上水"
  | "鴨脷洲"
  | "大角咀"
  | "黃大仙"
  | "土瓜灣"
  | "九龍灣"
  | "柯士甸"
  | "西營盤"
  | "中環"
  | "銅鑼灣"
  | "灣仔"
  | "跑馬地"
  | "堅尼地城"
  | "其他";

/** Popular districts (UI order); 康城 maps to 將軍澳+康城 sub區 in search logic */
export const DISTRICTS: District[] = [
  "沙田",
  "大圍",
  "馬鞍山",
  "大埔",
  "西貢",
  "將軍澳",
  "啟德",
  "九龍站",
  "奧運",
  "荃灣",
  "屯門",
  "元朗",
  "天水圍",
  "北角",
  "鰂魚涌",
  "康城",
  "南昌",
  "黃竹坑",
  "九龍城",
  "觀塘",
  "深水埗",
  "尖沙咀",
  "佐敦",
  "油麻地",
  "旺角",
  "紅磡",
  "何文田",
  "葵涌",
  "上水",
  "鴨脷洲",
  "大角咀",
  "黃大仙",
  "土瓜灣",
  "九龍灣",
  "柯士甸",
  "西營盤",
  "中環",
  "銅鑼灣",
  "灣仔",
  "跑馬地",
  "堅尼地城",
];

export type PropertyType = "住宅" | "居屋" | "村屋" | "唐樓";

export const PROPERTY_TYPES: PropertyType[] = ["住宅", "居屋", "村屋", "唐樓"];

export type SortOption =
  | "price_asc"
  | "price_desc"
  | "psf_asc"
  | "psf_desc"
  | "area_asc"
  | "area_desc";

// ─── Market summary (aggregated from search results) ────────────────────────
export interface MarketSummary {
  count: number;
  avgPrice: number;
  avgPsf: number;
  minPrice: number;
  maxPrice: number;
  priceRange: { label: string; count: number }[];
}
