import { ImageResponse } from "next/og";
import { SITE_CONFIG } from "@/lib/config";

/**
 * Site-wide default Open Graph image (1200×630).
 *
 * Auto-generated by Next.js when any page links to it via metadata.openGraph.
 * Per-page OG images can override (e.g. app/listing/[slug]/opengraph-image.tsx).
 */

export const runtime = "edge";
export const alt = SITE_CONFIG.name;
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OpenGraphImage(): Promise<ImageResponse> {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          background: "linear-gradient(135deg, #1e3a8a 0%, #1e40af 60%, #2563eb 100%)",
          color: "white",
          fontFamily: "system-ui, sans-serif",
        }}
      >
        <div style={{ fontSize: 88, fontWeight: 800, letterSpacing: -2 }}>
          {SITE_CONFIG.name}
        </div>
        <div
          style={{
            marginTop: 24,
            fontSize: 36,
            opacity: 0.9,
            maxWidth: 900,
            textAlign: "center",
            lineHeight: 1.4,
          }}
        >
          {SITE_CONFIG.tagline}
        </div>
        <div
          style={{
            marginTop: 56,
            fontSize: 22,
            opacity: 0.7,
            display: "flex",
            gap: 20,
          }}
        >
          <span>新樓盤</span>
          <span>·</span>
          <span>二手對比</span>
          <span>·</span>
          <span>按揭計算</span>
          <span>·</span>
          <span>戶型呎價</span>
        </div>
      </div>
    ),
    { ...size }
  );
}
